# name: Deploy New Training Script to viam-dev Org

description: 'Deploy New Training Script to viam-dev Org'
inputs:
  api_key_id:
    type: string 
    required: true
  api_key:
    type: string
    required: true
  framework:
    type: string
    default: "unspecified"
  script_name:
    type: string
    required: true
  type:
    type: string
    default: "unspecified"
  version:
    type: string
    required: true
  org_id:
    type: string
    required: true


name: Deploy ML Script

runs:
  using: "composite"
  steps:
    - name: Check out training script code
      uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Viam CLI
      shell: bash
      run: |
        curl -o /usr/local/bin/viam https://storage.googleapis.com/packages.viam.com/apps/viam-cli/viam-cli-stable-linux-amd64
        chmod a+rx /usr/local/bin/viam

    - name: Create training package
      shell: bash
      run: |
        python3 setup.py sdist --formats=gztar

    - name: Login to Viam CLI
      shell: bash
      run: |
        viam login api-key --key-id ${{ inputs.api_key_id }} --key ${{ inputs.api_key }}

    - name: Push to Viam Registry
      shell: bash
      run: |
        viam training-script upload --framework=${{inputs.framework}} --org-id=${{inputs.org_id}} --path=dist/model-0.1.tar.gz --script-name=${{inputs.script_name}} \
          --type=${{inputs.type}} --version=${{inputs.version}} --type=${{inputs.type}}
