name: Deploy ML Training Image

on:
  workflow_call:
    secrets:
      API_KEY_ID:
        required: true
      API_KEY:
        required: true
    inputs:
      framework:
        type: string
        default: "unspecified"
      script_name:
        type: string
        required: true
      type:
        type: string
        default: "unspecified"

jobs:
  deploy-staging:
    runs-on: [ubuntu-latest]
    name: Rename testing container in staging and push to staging
    
    timeout-minutes: 30
    
    steps:
    - name: Get Version Tag
      id: get-image-tag
      run: |
        echo "version-tag=$(date -u +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_OUTPUT

    - name: Check out training script code
      uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Viam CLI
      shell: bash
      run: |
        curl -o /usr/local/bin/viam https://storage.googleapis.com/packages.viam.com/apps/viam-cli/viam-cli-stable-linux-amd64
        chmod a+rx /usr/local/bin/viam

    - name: Create training package
      shell: bash
      run: |
        python3 setup.py sdist --formats=gztar

    - name: Login to Viam CLI
      shell: bash
      run: |
        viam login api-key --key-id ${{ secrets.API_KEY_ID }} --key ${{ secrets.API_KEY }}

    - name: Push to Viam Registry
      shell: bash
      env:
        org_id: e76d1b3b-0468-4efd-bb7f-fb1d2b352fcb
      run: |
        viam training-script upload --framework=${{inputs.framework}} --org-id=${{env.org_id}} --path=dist/model-0.1.tar.gz --script-name=${{inputs.script_name}} --type=${{inputs.type}} --version=${{ steps.get-image-tag.outputs.version-tag }}


